"""baseline - existing schema

Revision ID: db977cad812e
Revises: 
Create Date: 2026-07-01 20:32:26.022656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db977cad812e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physical_machines', sa.Column('admin_disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('vpn_status_vpnserver', sa.Column('admin_disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_status_vpnserver', 'admin_disabled')
    op.drop_column('physical_machines', 'admin_disabled')
    # ### end Alembic commands ###